# Generated by Django 5.2.3 on 2025-06-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['tester', 'customer', 'team_lead', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
