# Generated by Django 5.2.3 on 2025-06-18 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_bug_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'team_manager'}, related_name='projects_managed_by_team_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'team_manager'}, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['tester', 'team_manager', 'customer', 'team_lead', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('product_manager', 'Product Manager'), ('engineering_manager', 'Engineering Manager'), ('team_manager', 'Team Manager'), ('team_lead', 'Team Lead'), ('developer', 'Developer'), ('tester', 'Tester'), ('customer', 'Customer')], max_length=30),
        ),
    ]
