# Generated by Django 5.2.3 on 2025-06-18 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_team_managers_team_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'developer'}, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
